### ISSUE TITLE
Links for demo and documentation are down

### ISSUE THREAD

**Issue by YetAnotherMinion** [RodionGork/FREJ#5]
The source forge links are all down, will they be coming back up?

**Comment by RodionGork** [comment]
Yes, I've seen this for few days already. The most horrible is that we host checkers for "interactive" codeabbey problems there and they are down too. If SF could not get back I'll need to think where to move them (with as few changes to code as possible)...

**Comment by RodionGork** [comment]
Glory! sourceforge is up again!

I was quite nervous since despite its awkwardness it is a convenient free hosting :)
